#!/usr/bin/env bash
set -e # halt script on error

bundle exec jekyll build
(cd ./_site && bundle exec htmlproofer --ignore-status-codes "999" --ignore-urls "/fonts.gstatic.com/,/assets/css/style.css?v=" --assume-extension ./)
